"""Shared contracts and protocol boundaries for Agentic RAG modules."""

from agentic_rag.core.contracts import (
    Answer,
    Chunk,
    Citation,
    ConversationMessage,
    EmbeddingInput,
    EmbeddingOutput,
    EvidenceResolutionInput,
    EvidenceResolutionOutput,
    LLMCompletionInput,
    LLMCompletionOutput,
    LLMStreamDelta,
    ModelRole,
    RerankInput,
    RerankOutput,
    RetrievalInput,
    RetrievalOutput,
    SearchResult,
    SourceDocumentChunks,
    SourceDocumentUpload,
    WorkflowRunInput,
    WorkflowRunOutput,
)

__all__ = [
    "Answer",
    "Chunk",
    "Citation",
    "ConversationMessage",
    "EmbeddingInput",
    "EmbeddingOutput",
    "EvidenceResolutionInput",
    "EvidenceResolutionOutput",
    "LLMCompletionInput",
    "LLMCompletionOutput",
    "LLMStreamDelta",
    "ModelRole",
    "RerankInput",
    "RerankOutput",
    "RetrievalInput",
    "RetrievalOutput",
    "SearchResult",
    "SourceDocumentChunks",
    "SourceDocumentUpload",
    "WorkflowRunInput",
    "WorkflowRunOutput",
]
